server:
  port:8003
  context-path:http://47.96.101.223

spring:
  datasource:
    url: jdbc:mysql://rm-bp1hqcxq33659343yco.mysql.rds.aliyuncs.com:3306/1011cs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ruilin@20190613rds

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml



# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
